### ISSUE TITLE
Any infos about the hardware part of the project ?

### ISSUE THREAD

**Issue by timotekken** [stickyvectors/16_step_sequencer#1]
Thanks

**Comment by stickyvectors** [comment]
nothing concrete I'm afraid. The short story is that I originally built a prototype with an Arduino Uno for the processor, but ran out of RAM due to the display. I am in the process of reworking the design to operate on SAMD21 chip instead which will be much better, but is not an insignificant re-spec because I need to add a load of logic-level shifters.
